### ISSUE TITLE
Migrate rilm.info/ft to rilm.org server

### ISSUE THREAD

**Issue by lcfink** [RILMMusicLit/rilm.info-ft#16]
See [this discussion in Slack](https://rilm.slack.com/archives/G0ETRKFQE/p1613681418000800).

- [ ] How is rilm.info mapped to `52.0.199.144`?
- [X] ~~Put this in the rilm.org-wordpress repo?~~
- [ ] Setup on rilm.org server

**Comment by ahwitz** [comment]
Re: the first point, Route53 plus, presumably, some sort of config in IIS.

Re: the second point, this isn't WordPress, so it wouldn't fit there as easily.

Only option would be something like the rapmm-publishers page, which we could do, but a few issues:
1) This has a LOT more content on it, so it's gonna bog down that repo a bit, and it's gonna be equally weird (if not more) for this to be accessible on all three sites.
2) I'm pretty sure your suggestion would require replacing all `rilm.info` URLs with `rilm.org`, and that would require a decent amount of digging on both our side and Aptara/HTC's side, because they still rely on these links for a decent amount of their stuff.

Would strongly recommend against that. Seems like there's no benefit to me other than Windows-ing our source control, and it causes a decent amount of problems in addition.

**Comment by lcfink** [comment]
So, given @ahwitz thoughts above, moving it to a separate repo is not the best path. I've edited the initial notes above.

Re rilm.info/ip mapping: I don't think this would be in IIS, because it would something would have to resolve rilm.org to 52.0.199.144 before IIS ever gets a whack at it. We'll need to figure this out.

**Comment by ahwitz** [comment]
Nginx on the MySQL server should be set up to accept `rilm.info` requests successfully.

When you have a moment: can you go back in to GoDaddy and double-check that the DNS records are actually correct? From a WHOIS, looks like they’re pointing to a different set of servers than Route53's records say they are, and I have a feeling there's some link between GoDaddy and Route53 that's not actually working, possibly because of that.

**Comment by lcfink** [comment]
@ahwitz Sorry for the delay - just getting back to this. 
![image](https://user-images.githubusercontent.com/13571515/112151620-d3958680-8bb7-11eb-9122-ed905def5234.png)

Does this look right?

**Comment by ahwitz** [comment]
Set up. My guess was correct, was a case of resetting DNS servers in GoDaddy.
